export const CARGOS = {
	PRESIDENTE: "PRESIDENTE",
	GOVERNADOR: "GOVERNADOR",
	SENADOR: "SENADOR",
	DEPUTADO_FEDERAL: "DEPUTADO FEDERAL",
	DEPUTADO_ESTADUAL: "DEPUTADO ESTADUAL",
	DEPUTADO_DISTRITAL: "DEPUTADO DISTRITAL",
};

export const CARGOS_VALIDOS = Object.values(CARGOS);
